name: bismillah_habitbuddy
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ^3.1.1

  
dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  iconly: ^1.0.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/habits.jpeg
    - assets/team.jpeg
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/Pacifico-Regular.ttf