// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-AVNLhZSq5YxxZa7uvbhNNZoChRtyalU',
    appId: '1:87545428341:web:2dc36e576d9b36f53fbb3c',
    messagingSenderId: '87545428341',
    projectId: 'habitbuddy-bb2a3',
    authDomain: 'habitbuddy-bb2a3.firebaseapp.com',
    storageBucket: 'habitbuddy-bb2a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtqb91eUjC9Qb8_Ylj-nMjhRvooF_M-ko',
    appId: '1:87545428341:android:046712df9d1837fc3fbb3c',
    messagingSenderId: '87545428341',
    projectId: 'habitbuddy-bb2a3',
    storageBucket: 'habitbuddy-bb2a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB16OY1kGMwfyJsjxLvdJCmfwDuXGBxbxg',
    appId: '1:87545428341:ios:d573c3fcdd84192b3fbb3c',
    messagingSenderId: '87545428341',
    projectId: 'habitbuddy-bb2a3',
    storageBucket: 'habitbuddy-bb2a3.firebasestorage.app',
    iosClientId: '87545428341-909er40mn4pcm5rium1bt8m7avhoni69.apps.googleusercontent.com',
    iosBundleId: 'com.example.bismillahHabitbuddy',
  );
}
